name: PR Closed

on:
  pull_request:
    branches: [main]
    types: [closed]

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [bitnami/postgresql, postgres/postgres]
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ github.event.repository.name }}/${{ matrix.package }}
          package-type: 'container'
          min-versions-to-keep: 50
          delete-only-untagged-versions: 'true'
