name: PR Closed

on:
  pull_request:
    branches: [main]
    types: [closed]

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  cleanup:
    name: Untagged container cleanup
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [bitnami/postgresql, bitnami/postgresql-ha, bitnami/pgpool, mongo, postgres]
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
        with:
          package-name: ${{ github.event.repository.name }}/${{ matrix.package }}
          package-type: 'container'
          min-versions-to-keep: 50
          delete-only-untagged-versions: 'true'
